# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        id: cache-llvm_project
        with:
          path:
            ./llvm-project
          key: ${{ runner.os }}-llvm_project
      - name: Install Visual Studio
        uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      - name: Install Clang
        run: |
          set-executionpolicy remotesigned -s cu
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop bucket add dorado https://github.com/chawyehsu/dorado
          scoop update
          scoop install llvm
          $env:path+="~\scoop\bin"
          git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git
          cd llvm-project
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../llvm
          make -j8
      - name: Get LLVM Source
        run: |
      - name: Prepare And Build
        run: |
      - name: Archive Release
        uses: vimtor/action-zip@v1
        with:
          dest: 'release.zip'
          files: 'llvm-project/build'
      - name: Publish Release
        uses: xresloader/upload-to-github-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: release.zip
      # Runs a set of commands using the runners shell
      - name: Finish
        run: finished
