# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            llvm-project
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Install Visual Studio
        uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      - name: Install Clang
        run: 
          winget install llvm
      - name: Get LLVM Source
        run: |
          git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git
      - name: Prepare And Build
        run: |
          cd llvm-project
          mkdir build
          cd build
          $env:CC="clang"
          $env:CXX="clang++"
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../llvm
          make -j16
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          directory: 'llvm-project/build'
      - name: Publish Release
        uses: xresloader/upload-to-github-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: release.zip
      # Runs a set of commands using the runners shell
      - name: Finish
        run: finished
